[package]
name = "multitool"
version = "0.1.0"
authors = ["wrmsr"]
edition = "2018"

[dependencies]
clap = "2.31.2"
hex = "0.4.0"
jmespath = "0.2.0"
serde = "1.0.101"
serde_cbor = "0.10.2"
serde_json = "1.0.40"
serde_yaml = "0.8.11"
regex = "1.3.1"
uuid = "0.7.4"
